services:
  postgres:
    image: postgres:latest
    container_name: postgres_yline
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresPassword
      POSTGRES_DB: yline
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:latest
    container_name: redis_yline
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:

# 注意保证这里的参数和 config 中的参数一致 (如果使用docker)
# postgres://username:password@host:port/database
