[server]
ip = "0.0.0.0"
port = 33383

[middleware]
# 只放行内网ip发来的http请求
IntranetIpFilter = false
# 只放行本机127.0.0.1或者::1发来的http请求
LocalHostFilter = false
# CORS跨域请求
CORS = false
CORSAllowOrigins = [
        "http://localhost:5173", # 允许本地开发环境
        # "*", # 允许所有来源, 注意不支持通配符写法，这更像一个开关，表示运行所有跨域请求
        # "http://example.com", # 允许特定来源, 例如独立部署的前端
    ]

[jwt]
secret = "your_secret"

[database]
# 注意保证这里的参数和 docker-compose 中的参数一致 (如果使用docker)
# postgres://username:password@host:port/database
host = "localhost"
port = 5432
db_user = "postgres"
db_password = "postgresPassword"
db_name = "yline"
connection_number = 10
timeout = 5.0

[logger]
level = "info"

[dbmate]
migration = true
download_url = "https://github.com/amacneil/dbmate/releases/download/v2.21.0"
win_name = "dbmate-windows-amd64.exe"
linux_name = "dbmate-linux-amd64"