[YLineWorker]
# YLineWorker 服务监听的ip和端口 
# YLineWorker service listen ip and port
ip = "0.0.0.0"
port = 33393

[worker]
# worker 的注册密钥，目前是对称加密，需要和 YLineServer 保持一致
register_secret = "your_register_secret"

[YLineServer]
# YLineServer 的ip和端口
# YLineServer's ip and port
ip = "127.0.0.1"
port = 33383

[middleware]
# 只放行内网ip发来的http请求 only allow intranet ip
IntranetIpFilter = false
# 只放行本机127.0.0.1或者::1发来的http请求 ony allow localhost ip
LocalHostFilter = false

[logger]
level = "info"
