function(YSolowork_message msg)
    if (NOT YSolowork_QUIET)
      message(STATUS "${msg}")
    endif()
endfunction()

if(CMAKE_BUILD_TYPE)
    # message(STATUS "Current Build Type: ${CMAKE_BUILD_TYPE}")
    set(YSolowork_BUILD_TYPE ${CMAKE_BUILD_TYPE})
elseif(CMAKE_CONFIGURATION_TYPES)
    # message(STATUS "Available Configurations: ${CMAKE_CONFIGURATION_TYPES}")
    set(YSolowork_BUILD_TYPE ${CMAKE_CONFIGURATION_TYPES})
else()
    # message(STATUS "No build type or configuration specified.")
    set(YSolowork_BUILD_TYPE "None")
endif()

YSolowork_message("┌─ YSolowork options ─────────────────────")
YSolowork_message("│ YSolowork_BUILD_TYPE      : ${YSolowork_BUILD_TYPE}")
YSolowork_message("│ BUILD_YLINESERVER         : ${BUILD_YLINESERVER}")
YSolowork_message("│ BUILD_YLINEWORKER         : ${BUILD_YLINEWORKER}")
YSolowork_message("│ YSolowork_QUIET           : ${YSolowork_QUIET}")
YSolowork_message("└───────────────────────────────────────")